language: java

jdk:
  - openjdk8

before_script:
  - if [ ! -z "$TRAVIS_TAG" ]; then mvn versions:set -DnewVersion=$TRAVIS_TAG; fi

script:
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: LJjZzy9i0OmNJrav71LbyP7kP9oWzkUXgwCnG95b2bzrDnVw0OQVDpU3nQXB9w0AKgF4CCsHMLo6k383n9LQ+f/AGO91a3urya3Rns+Y7Y6ptk3ZRXA39U7/5Eod8lWApd18l+EWvansZEzkukHH0xXGK+SWuTo5taH6PKmrEQKjw9zxMI07+9lIJcN7vddQzdFanCaincz4pW/EgLIhJXcecyprDjnYQnbEVczYsp7W2+XbLn/rhE7vxK/ZCU1nJojUD3YwMrQgBj5MaiAtAEYSwvuq5N9jpR1glEIqlmhw5kdhLIt+R3FlMicWPhKPW/7t7RmCFAxDclkBaJT+RBF/438wZwUXLZ4KbeAcgB3zRkgK1qVpxx/jJF0Q1zHzrRF1tsJSILI7yJBpE+JPp/881JwLJnUgbuAAWy282m9Kd5G3DL7yhkWlG+Jrau6iN89kh+Nko7KtZ3bosvyzne9cgC+AubTY3pF+BebKA0ZQarolhY24U9yOKDmo1gvllEbnlSsV5N3ga7zhZ6rHMpN/X+3qqn9awffHvXsG0dJpXk968c2FzSgwMk7ibcN1vFcSf0MkByOE5iiZDjOpzS4FOi6j70XLfX+8NI/QcP63jXO7oXzNBBWhQaXM/VrHt0oNP2u56UZTKDmgW+9BSIQtIKRCd3FxKfNtr/ES1ms=
  file_glob: true
  file: target/*.jar
  skip_cleanup: true
  on:
    tags: true
